name: .cenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.7.0
  - scikit-learn=1.6.1
  - faker=37.1.0
  - matplotlib=3.10.3
  - pandas=2.2.3
  - numpy=2.2.5
  - seaborn=0.12.2
